### ISSUE TITLE
Archive / Make This Repo Private

### ISSUE THREAD

**Issue by yanicakj** [decentralized-identity/uni-resolver-driver-did-work#8]
Hi @peacekeeper & @BernhardFuchs,

We would like to archive or make this repo private as this DID method is being sunset & has no plans for continued support in the future.

A PR has already been merged to remove it from the main universal-resolver repo here: https://github.com/decentralized-identity/universal-resolver/pull/353

We would also like to remove this driver from DIF's DockerHub repo if that could also be done?: https://hub.docker.com/r/universalresolver/driver-did-work

Please let me know, thanks again 👍

**Comment by BernhardFuchs** [comment]
Hi Jacob,​​  

we've archived the repository on Github and removed the images on Dockerhub.​  
If someone still wants to run the driver, there is the option to fork the repo on Github and build an image themselves.  

​​Guess this serves everyone needs.

Btw, comments on Issues are not possible at archived repositories
